using Content.Shared.Cards;
using Content.Shared.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Cards;
[GenerateTypedNameReferences]
public sealed partial class CardInspect : BoxContainer
{
    public CardListVisualState? VisualState { get; set; }
    public CardInspect()
    {
        RobustXamlLoader.Load(this);
    }
}
